name = "ninja-pve-leaderboard"
compatibility_date = "2026-07-05"
pages_build_output_dir = "public"

[vars]
TARGET_GAME_URL = "https://ninjazenshin.online/pve-leaderboard"

[[kv_namespaces]]
binding = "LEADERBOARD_KV"
id = "dcf7d4858257402aaf72f98f94839350"

[[kv_namespaces]]
binding = "KV"
id = "dcf7d4858257402aaf72f98f94839350"
